[[redirects]]
  from = "https://estate.machaccounting.com/*"
  to = "https://cra.machaccounting.com/estate.html"
  status = 200
  force = true

[[redirects]]
  from = "https://foreign.machaccounting.com/*"
  to = "https://cra.machaccounting.com/foreign.html"
  status = 200
  force = true